@Is{!Environment.AccountName}
private class SampleClass{!Environment.AccountName} {
    
    @Is{!Environment.AccountName}
    private static void getStringData{!Environment.AccountName}() {
        SampleClass.getStringData();
    }
    
    @Is{!Environment.AccountName}
    private static void getBooleanData{!Environment.AccountName}() {
        SampleClass.getBooleanData();
    }
    
    @Is{!Environment.AccountName}
    private static void getIntegerData{!Environment.AccountName}() {
        SampleClass.getIntegerData();
    }
}